kmiri: allowing multiple AllocIds point to the same addr causes UB
error: Undefined Behavior: constructing invalid value of type core::fmt::Arguments<'_>: at .template, encountered 0, but expected something greater or equal
to 1
   --> /home/zjp/.rustup/toolchains/nightly-2026-04-03-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/fmt/mod.rs:236:33
    |
236 |                     write(self, args)
    |                                 ^^^^ Undefined Behavior occurred here
    |
    = help: this indicates a bug in the program: it performed an invalid operation, and caused Undefined Behavior
    = help: see https://doc.rust-lang.org/nightly/reference/behavior-considered-undefined.html for further information
    = note: stack backtrace:
            0: <&mut ostd::arch::MiriStdout as core::fmt::Write::write_fmt::SpecWriteFmt>::spec_write_fmt
                at /home/zjp/.rustup/toolchains/nightly-2026-04-03-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/fmt/mod.rs:236:33: 236:37
            1: <ostd::arch::MiriStdout as core::fmt::Write>::write_fmt
                at /home/zjp/.rustup/toolchains/nightly-2026-04-03-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/fmt/mod.rs:241:9: 241:34
            2: ostd::arch::_miri_print
                at /home/zjp/KMiri/asterinas/ostd/src/arch/miri/mod.rs:141:5: 141:31
            3: miri_start
                at /home/zjp/KMiri/asterinas/ostd/src/lib.rs:39:9: 39:69