kmiri: print min_allocated_stack_addr and next_stack_addr
We can see the bug is min_allocated_stack_addr remains while next_stack_addr varies,
and stack variables are lower than next stack, meaning stack has been overridden and
caused the double free via base addr.

min_allocated_stack_addr=None next_stack_addr=ffffffff80fffff8
min_allocated_stack_addr=Some("[0xfffff0, 0xfffff8) size= 8B alloc87") next_stack_addr=ffffffff80fffff0
min_allocated_stack_addr=Some("[0xffffe8, 0xfffff0) size= 8B alloc88") next_stack_addr=ffffffff80ffffe0
min_allocated_stack_addr=Some("[0xffffd0, 0xffffe0) size=16B alloc89") next_stack_addr=ffffffff80ffffc8
min_allocated_stack_addr=Some("[0xffffb0, 0xffffc8) size=24B alloc90") next_stack_addr=ffffffff80ffffc0
min_allocated_stack_addr=Some("[0xffffb0, 0xffffc8) size=24B alloc90") next_stack_addr=ffffffff80ffffc0
min_allocated_stack_addr=Some("[0xffffb0, 0xffffc8) size=24B alloc90") next_stack_addr=ffffffff80ffffc0
min_allocated_stack_addr=Some("[0xffffb0, 0xffffc8) size=24B alloc90") next_stack_addr=ffffffff80ffffc0
min_allocated_stack_addr=Some("[0xffffb8, 0xffffc0) size= 8B alloc95") next_stack_addr=ffffffff80ffffb0
min_allocated_stack_addr=Some("[0xffffa0, 0xffffb0) size=16B alloc96") next_stack_addr=ffffffff80ffffa0
min_allocated_stack_addr=Some("[0xffff90, 0xffffa0) size=16B alloc97") next_stack_addr=ffffffff80ffff90
min_allocated_stack_addr=Some("[0xffff80, 0xffff90) size=16B alloc98") next_stack_addr=ffffffff80ffffc0
min_allocated_stack_addr=Some("[0xffff80, 0xffff90) size=16B alloc98") next_stack_addr=ffffffff80ffffc0
min_allocated_stack_addr=Some("[0xffff80, 0xffff90) size=16B alloc98") next_stack_addr=ffffffff80ffffc0
min_allocated_stack_addr=Some("[0xffff80, 0xffff90) size=16B alloc98") next_stack_addr=ffffffff80ffffc0
min_allocated_stack_addr=Some("[0xffff80, 0xffff90) size=16B alloc98") next_stack_addr=ffffffff80ffffb0
min_allocated_stack_addr=Some("[0xffff80, 0xffff90) size=16B alloc98") next_stack_addr=ffffffff80ffffa0
min_allocated_stack_addr=Some("[0xffff80, 0xffff90) size=16B alloc98") next_stack_addr=ffffffff80ffff90
min_allocated_stack_addr=Some("[0xffff80, 0xffff90) size=16B alloc98") next_stack_addr=ffffffff80ffffc0
min_allocated_stack_addr=Some("[0xffff80, 0xffff90) size=16B alloc98") next_stack_addr=ffffffff80ffffc0
min_allocated_stack_addr=Some("[0xffff80, 0xffff90) size=16B alloc98") next_stack_addr=ffffffff80ffffc0
min_allocated_stack_addr=Some("[0xffff80, 0xffff90) size=16B alloc98") next_stack_addr=ffffffff80ffffc0
min_allocated_stack_addr=Some("[0xffff80, 0xffff90) size=16B alloc98") next_stack_addr=ffffffff80ffffb0
min_allocated_stack_addr=Some("[0xffff80, 0xffff90) size=16B alloc98") next_stack_addr=ffffffff80ffffa0
min_allocated_stack_addr=Some("[0xffff80, 0xffff90) size=16B alloc98") next_stack_addr=ffffffff80ffff90
min_allocated_stack_addr=Some("[0xffff80, 0xffff90) size=16B alloc98") next_stack_addr=ffffffff80ffff98

thread 'rustc' (48341) panicked at src/alloc_addresses/mod.rs:841:9:
assertion `left == right` failed
  left: (16777104, alloc98)
 right: (16777104, alloc114)